# =========================================================
#  Konfiguracja pluginu SpiderHunt
#  Wartosci cooldownow podane sa w sekundach.
#  Zmiany zaczna obowiazywac po restarcie serwera
#  (bez potrzeby rekompilacji pluginu).
# =========================================================

spider_sword:
  cooldown_seconds: 10

spider_trap:
  cooldown_seconds: 15
